### ISSUE TITLE
Module connectivity.js not found (mongoose)

### ISSUE THREAD

**Issue by HendrikRoth** [strapi/strapi-docker#127]
Tried to run the latest strapi/strapi docker image. Any ideas?

```
🚀 Starting to create your Strapi application.
Database determined by CLI args: mongo
⏳ Testing database connection...
It might take a minute, please have a coffee ☕️

{ Error: Cannot find module '/tmp/strapi94876701a408/node_modules/strapi-hook-mongoose/lib/utils/connectivity.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Promise.all.then (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:377:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7) code: 'MODULE_NOT_FOUND' }

Error: An error occurred. The error exit was triggered on a switchback that is being handled with a callback function in userland. And since no truthy argument was provided, switchback created this anonymous error.

    at Function.error (/usr/local/lib/node_modules/strapi/node_modules/switchback/lib/normalize.js:41:23)
    at Promise.all.then (/usr/local/lib/node_modules/strapi/node_modules/strapi-generate-new/lib/before.js:382:14)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

🚀 Starting to create your Strapi application.
```

**Comment by HendrikRoth** [comment]
found the issue: https://github.com/npm/npm/issues/16661
(my docker network had no access to the internet)
