### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by spijs** [strapi/strapi-docker#141]
I'm trying to set up strapi using docker compose with following configuration :

> DATABASE_CLIENT=mongo
> DATABASE_HOST=url-x0sru.mongodb.net
> DATABASE_USERNAME=user
> DATABASE_PASSWORD=password
> DATABASE_PORT=27017
> DATABASE_NAME=strapi
> DATABASE_SRV=true
> DATABASE_AUTHENTICATION_DATABASE=admin
> DATABASE_SSL=true

When I attach myself to the container I see the following output:

> internal/modules/cjs/loader.js:589
>     throw err;
>     ^
> Error: Cannot find module 'lodash'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:513:25)
>     at Module.require (internal/modules/cjs/loader.js:643:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (/usr/src/api/strapi-app/admin/controllers/Admin.js:5:11)
>     at Module._compile (internal/modules/cjs/loader.js:707:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
>     at Module.load (internal/modules/cjs/loader.js:605:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:536:3)

**Comment by spijs** [comment]
adding `RUN npm install lodash` as a second step in my Dockerfile seems to (temporarily solve the issue)

**Comment by spijs** [comment]
Apparently this has to do with previous runs of the build. Once I removed the associated volumes and let it fully retry it worked :)
