### ISSUE TITLE
Strapi 3.4.2 docker-compose fails due to `sharp` build error: `ERR! sharp EPERM: operation not permitted`

### ISSUE THREAD

**Issue by virgil9306** [strapi/strapi-docker#270]
### Describe the bug

* On OSX Catalina and Strapi `3.4.2` docker images, running `strapi/strapi` in docker-compose fails.
* This error did not occur previously (`3.1.5` was the last version I used before I saw this error happen).
* Since [`strapi-plugin-upload`](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/package.json) uses `sharp` I wonder if that may be related.

Here is the error message:

```

strapi_1  | error /srv/app/node_modules/sharp: Command failed.
strapi_1  | Exit code: 1
strapi_1  | Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
strapi_1  | Arguments:
strapi_1  | Directory: /srv/app/node_modules/sharp
strapi_1  | Output:
strapi_1  | info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br
strapi_1  | ERR! sharp EPERM: operation not permitted, link '/srv/app/node_modules/sharp/vendor/8.10.0/include/pnglibconf.h' -> '/srv/app/node_modules/sharp/vendor/8.10.0/include/libpng16/pnglibconf.h'
strapi_1  | info sharp Attempting to build from source via node-gyp but this may fail due to the above error
strapi_1  | info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
strapi_1  | gyp info it worked if it ends with ok
strapi_1  | gyp info using node-gyp@5.1.0
strapi_1  | gyp info using node@12.20.1 | linux | x64
strapi_1  | gyp info find Python using Python version 2.7.13 found at "/usr/bin/python"
strapi_1  | gyp http GET https://nodejs.org/download/release/v12.20.1/node-v12.20.1-headers.tar.gz
strapi_1  | gyp http 200 https://nodejs.org/download/release/v12.20.1/node-v12.20.1-headers.tar.gz
strapi_1  | gyp http GET https://nodejs.org/download/release/v12.20.1/SHASUMS256.txt
strapi_1  | gyp http 200 https://nodejs.org/download/release/v12.20.1/SHASUMS256.txt
strapi_1  | gyp info spawn /usr/bin/python
strapi_1  | gyp info spawn args [
strapi_1  | gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
strapi_1  | gyp info spawn args   'binding.gyp',
strapi_1  | gyp info spawn args   '-f',
strapi_1  | gyp info spawn args   'make',
strapi_1  | gyp info spawn args   '-I',
strapi_1  | gyp info spawn args   '/srv/app/node_modules/sharp/build/config.gypi',
strapi_1  | gyp info spawn args   '-I',
strapi_1  | gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
strapi_1  | gyp info spawn args   '-I',
strapi_1  | gyp info spawn args   '/root/.cache/node-gyp/12.20.1/include/node/common.gypi',
strapi_1  | gyp info spawn args   '-Dlibrary=shared_library',
strapi_1  | gyp info spawn args   '-Dvisibility=default',
strapi_1  | gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/12.20.1',
strapi_1  | gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
strapi_1  | gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/12.20.1/<(target_arch)/node.lib',
strapi_1  | gyp info spawn args   '-Dmodule_root_dir=/srv/app/node_modules/sharp',
strapi_1  | gyp info spawn args   '-Dnode_engine=v8',
strapi_1  | gyp info spawn args   '--depth=.',
strapi_1  | gyp info spawn args   '--no-parallel',
strapi_1  | gyp info spawn args   '--generator-output',
strapi_1  | gyp info spawn args   'build',
strapi_1  | gyp info spawn args   '-Goutput_dir=.'
strapi_1  | gyp info spawn args ]
strapi_1  | gyp info spawn make
strapi_1  | gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
strapi_1  | make: Entering directory '/srv/app/node_modules/sharp/build'
strapi_1  |   CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
strapi_1  |   AR(target) Release/obj.target/../node-addon-api/nothing.a
strapi_1  |   COPY Release/nothing.a
strapi_1  |   TOUCH Release/obj.target/libvips-cpp.stamp
strapi_1  |   CXX(target) Release/obj.target/sharp/src/common.o
strapi_1  | ../src/common.cc:24:22: fatal error: vips/vips8: No such file or directory
strapi_1  |  #include <vips/vips8>
strapi_1  |                       ^
strapi_1  | compilation terminated.
strapi_1  | make: *** [Release/obj.target/sharp/src/common.o] Error 1
strapi_1  | sharp.target.mk:139: recipe for target 'Release/obj.target/sharp/src/common.o' failed
strapi_1  | make: Leaving directory '/srv/app/node_modules/sharp/build'
strapi_1  | gyp ERR! build error
strapi_1  | gyp ERR! stack Error: `make` failed with exit code: 2
strapi_1  | gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
strapi_1  | gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
strapi_1  | gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
strapi_1  | gyp ERR! System Linux 4.14.154-boot2docker
strapi_1  | gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
strapi_1  | gyp ERR! cwd /srv/app/node_modules/sharp
strapi_1  | gyp ERR! node -v v12.20.1
strapi_1  | gyp ERR! node-gyp -v v5.1.0
strapi_1  | gyp ERR! not ok
strapi_1  |
strapi_1  |  Keep trying!
strapi_1  |
strapi_1  | Oh, it seems that you encountered errors while installing dependencies in your project.
strapi_1  | Don't give up, your project was created correctly.
strapi_1  | Fix the issues mentionned in the installation errors and try to run the following command:
strapi_1  |
strapi_1  | cd /srv/app && yarn install
strapi_1  |
strapi_strapi_1 exited with code 1
```

### Steps to reproduce the behavior

1. Using the above `docker-compose.yaml` on 

### Expected behavior

Previously the build succeeded here.

### Screenshots

N/A

### Code snippets

See "Additional Context" at the end

### System

- Node.js version: Using `strapi/strapi` so same version as that (unsure). Local system is running Node `v12.18.3`
- NPM version: Using `strapi/strapi` so same version as that (unsure). Local system is running npm `v6.14.6`
- Strapi version: 3.4.2, 3.4.1
- Database: MariaDB
- Operating system: OSX Catalina latest updates

### Additional context

* I did not notice this error when using `strapi/base` to use a `Dockerfile` to build a Strapi image. I only noticed this issue when running in `docker-compose` using `strapi/strapi`.
* Should it be running as `root` in order to compile this? Or is there another way to get this dependency?
* The version pulled is `3.4.2`
* `docker-compose.yaml` file:

```
version: '3'
services:
  strapi:
    image: strapi/strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
```

* `package.json` from `strapi/strapi`: 

```
{
  "name": "app",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.4.2",
    "strapi-admin": "3.4.2",
    "strapi-utils": "3.4.2",
    "strapi-plugin-content-type-builder": "3.4.2",
    "strapi-plugin-content-manager": "3.4.2",
    "strapi-plugin-users-permissions": "3.4.2",
    "strapi-plugin-email": "3.4.2",
    "strapi-plugin-upload": "3.4.2",
    "strapi-connector-bookshelf": "3.4.2",
    "knex": "<0.20.0",
    "sqlite3": "latest"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "1bb363b8-d150-460c-8d12-1e460b84ca56"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by virgil9306** [comment]
Update:

I have identified this as a permissions issue for Docker under OSX when mounting a directory and running the compile tools for `sharp`.

Previously `sharp` did not trigger this issue. 

But the conditions for meeting this error are:

* OSX
* docker-machine
* Using `sharp` package

Problem does not occur when I use `volumes` rather than mounting a directory.

So this does not seem to be a `strapi-docker` issue BUT it may be a compatibility issue with the later version of `sharp`, so I am not sure if this should be a "FAQ" or something for OSX users.

**Comment by alexandrebodin** [comment]
Hi @virgil9306 thank you for all those details. Doesn't look like we can do much for now. Let me know if you find anything we can do on our side

**Comment by virgil9306** [comment]
Hi @alexandrebodin 

I am not sure why I did not encounter this error before. But it seems to be an unavoidable situation due to the dependency.

I hope someone else using Linux or OSX and `docker-machine` with shared folders mounted to the Strapi container can verify this.

Unfortunately I think I will need to create a workaround that for my workflow.

**Comment by Kyle772** [comment]
I ran into this problem and after trying to work through it for a couple days I ended up fixing it/avoiding it by creating a new container and volume, resetting my docker to factory settings (maybe unnecessary), adding libvips as a dependency, and rebuilding. I think the error is on sharps end honestly but I truly have no idea. 

The issue first popped up for me when I tried to develop on my Mac (not M1; which some threads were suggesting) after previously working on WSL2. The issue seemed to point to a bad link between sharp and libvips. 

A lot of threads I was finding on this suggest using `npm install --ignore-scripts=false --verbose` but this didn't fix the issue for me.

No clue if this will help anyone but hopefully it'll give some more context to anyone in need.

**Comment by nonameolsson** [comment]
Thanks @Kyle772! I can confirm that this problem exists, happens to me as well. Haven't tried your solution yet though.

**Comment by csibivili** [comment]
Same issue here.
macOS Catalina (latest)
followed this guide: https://strapi.io/blog/how-to-run-a-strapi-dev-stack-with-docker-compose

**Comment by Ulibka68** [comment]
Windows 10, WSL 2, docker
I have the same issue with sharp.
Is anybody know how to fix it?

**Comment by Ulibka68** [comment]
Yesterday I'm removing all images from docker and start building again - all is work ! (windows 10, wsl2)

**Comment by jpcmf** [comment]
Same issue here. Windows 10 Pro, WSL2, Docker. I removed everthing and it´s not building yet. Any help? Thanks

```
#9 102.7 [5/5] Building fresh packages...
#9 104.8 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#9 104.8 error /app/node_modules/sharp: Command failed.
#9 104.8 Exit code: 1
#9 104.8 Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
#9 104.8 Arguments:
#9 104.8 Directory: /app/node_modules/sharp
#9 104.8 Output:
#9 104.8 sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.11.3/libvips-8.11.3-linux-x64.tar.br
#9 104.8 sharp: Installation error: self signed certificate in certificate chain
#9 104.8 sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
------
executor failed running [/bin/sh -c yarn install --frozen-lockfile]: exit code: 1
```
