### ISSUE TITLE
Installation Failed using docker : Error response from daemon: status code not OK but 500

### ISSUE THREAD

**Issue by egyleader** [strapi/strapi-docker#311]
## Bug report
When following this tutorial for installing Strapi using docker 
https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html#creating-a-strapi-project

it completes docker-compose pull successfully 
but when running docker-composer up
it fails with this error log :
```
[+] Running 0/1
 - Container strapi-docker-test_mysql_1  Creating                                                                                      1.8s 
Error response from daemon: status code not OK but 500:     ����       
                                                                          BDocker.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken
Error response from daemon: status code not OK but 500:     ����       
                                     ClassNameMessageDataInnerException   BDocker.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken
=null  ocker.Core.DockerException.IDictionarySystem.Excepti     ocker.Core.DockerException   Filesharing has been cancelle
d                                    ClassNameMessageDataInnerExceptionHelpURLStackTraceStringRemoteStackTraceStringRemoteStackInde
WatsonBuckets  System.Collections.IDictionarySystem.Excepti     ocker.Core.DockerException   Filesharing has been cancelle
d


   �   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__7.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\wi
n\src\Docker.ApiServices\Mounting\FileSharing.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Mounting.FileSharing.<ShareAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpApi.Controllers.FilesharingController.<ShareDirectory>d__2.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.HttpApi\Controllers\FilesharingController.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
       �8
MoveNext
Docker.ApiServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Docker.ApiServices.Mounting.FileSharing+<DoShareAsync>d__7
Void MoveNext() �   Docker.ApiServices
```
.

### System
- Windows 10 pro 
- docker version  20.10.7, build f0df350

**Comment by derrickmehaffy** [comment]
Transferring issue to docker repo
