### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by danielivert** [strapi/strapi-docker#40]
Hello,

I am getting the following error when I am trying to run the image after having it pulled.

```
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
Database determined by CLI args: mongo

⏳ Testing database connection...
{ Error: Command failed: yarn install --production --ignore-scripts
error An unexpected error occurred: "https://registry.yarnpkg.com/react-ga: getaddrinfo EAI_AGAIN registry.yarnpkg.com:443".

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at ChildProcess.emit (domain.js:422:20)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'yarn install --production --ignore-scripts' }
```

Any ideas what that could be?

Thanks for the help

**Comment by lucaperret** [comment]
Hello @danielivert , do you try to install behind a proxy ? it seems yarn cannot connect to the network.

**Comment by lucaperret** [comment]
You should configure `HTTPS_PROXY`,  `HTTP_PROXY`, `ALL_PROXY`, `NO_PROXY` environment variables.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.
