### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ouchiko** [strapi/strapi-docker#46]
I've tried latest back through to older docker tags and I can't get this running. Run as image pull and direct on the Dockerfile also.

Primary issue continually seems to be:

```
api_1    | error TypeError: strapi.models.core_store.forge is not a function
api_1    |     at Object.get (/usr/local/lib/node_modules/strapi/lib/core/store.js:55:47)
api_1    |     at module.exports (/usr/src/api/strapi-app/plugins/content-manager/config/functions/bootstrap.js:229:42)
api_1    |     at Promise (/usr/local/lib/node_modules/strapi/lib/Strapi.js:285:13)
api_1    |     at new Promise (<anonymous>)
api_1    |     at execBootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:273:11)
api_1    |     at Promise.all.Object.values.map.x (/usr/local/lib/node_modules/strapi/lib/Strapi.js:312:44)
api_1    |     at Array.map (<anonymous>)
api_1    |     at Strapi.bootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:312:35)
api_1    |     at Strapi.start (/usr/local/lib/node_modules/strapi/lib/Strapi.js:107:18)
api_1    |     at <anonymous>
api_1    | (node:15) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
api_1    |     at Object.get (/usr/local/lib/node_modules/strapi/lib/core/store.js:55:47)
api_1    |     at module.exports (/usr/src/api/strapi-app/plugins/settings-manager/config/functions/bootstrap.js:17:26)
api_1    |     at Promise (/usr/local/lib/node_modules/strapi/lib/Strapi.js:285:13)
api_1    |     at new Promise (<anonymous>)
api_1    |     at execBootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:273:11)
api_1    |     at Promise.all.Object.values.map.x (/usr/local/lib/node_modules/strapi/lib/Strapi.js:312:44)
api_1    |     at Array.map (<anonymous>)
api_1    |     at Strapi.bootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:312:35)
api_1    |     at Strapi.start (/usr/local/lib/node_modules/strapi/lib/Strapi.js:107:18)
api_1    |     at <anonymous>
api_1    | (node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
api_1    | (node:15) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
api_1    | [2018-08-28T10:16:02.269Z] warn Bootstrap is taking unusually long to execute its callback 3500 miliseconds).
api_1    | [2018-08-28T10:16:02.271Z] warn Perhaps you forgot to call it?
```

Node @ v9 on the Strapi API 
`/usr/src/api/strapi-app # node -v
v9.11.1`

```
"dependencies": {
    "lodash": "4.x.x",
    "strapi": "3.0.0-alpha.13.1",
    "strapi-hook-mongoose": "3.0.0-alpha.13.1"
  },
```

The image installation via Dockerfile is OK.

```
root@strapi:~/strapi-docker# docker-compose up
Building api
Step 1/10 : FROM node:9.11.1-alpine
9.11.1-alpine: Pulling from library/node
605ce1bd3f31: Already exists
7cc38010b685: Already exists
88a635599bc5: Already exists
Digest: sha256:f8f6c69cce180a9a7c9fa685c86671b1e1f2ea7cc5f9a0dbe99d30cc7a0b6cbe
Status: Downloaded newer image for node:9.11.1-alpine
 ---> 9cc7800b3f3c
Step 2/10 : LABEL maintainer="Luca Perret <perret.luca@gmail.com>"       org.label-schema.vendor="Strapi"       org.label-schema.name="Strapi Docker image"       org.label-schema.description="Strapi containerized"       org.label-schema.url="https://strapi.io"       org.label-schema.vcs-url="https://github.com/strapi/strapi-docker"       org.label-schema.version=latest       org.label-schema.schema-version="1.0"
 ---> Running in 06747ceeb7e9
Removing intermediate container 06747ceeb7e9
 ---> ba15448a1d0e
Step 3/10 : WORKDIR /usr/src/api
Removing intermediate container d60f419808c2
 ---> 8a03bb768927
Step 4/10 : RUN npm install -g strapi@3.0.0-alpha.13.1
 ---> Running in 455e0c7dca8c
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm WARN notice [SECURITY] deep-extend has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=deep-extend&version=0.2.11 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.10.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.6.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=4.17.4 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
/usr/local/bin/strapi -> /usr/local/lib/node_modules/strapi/bin/strapi.js
+ strapi@3.0.0-alpha.13.1
added 391 packages in 21.617s
Removing intermediate container 455e0c7dca8c
 ---> 37bafa272a09
Step 5/10 : COPY strapi.sh ./
 ---> e10df39a92d4
Step 6/10 : RUN chmod +x ./strapi.sh
 ---> Running in 10889a82b0ac
Removing intermediate container 10889a82b0ac
 ---> 20e89447b146
Step 7/10 : EXPOSE 1337
 ---> Running in 65ef7067ed7a
Removing intermediate container 65ef7067ed7a
 ---> 8a5167500fdc
Step 8/10 : COPY healthcheck.js ./
 ---> 8d3dbb4f7d28
Step 9/10 : HEALTHCHECK --interval=15s --timeout=5s --start-period=30s       CMD node /usr/src/api/healthcheck.js
 ---> Running in 0162f62e4435
Removing intermediate container 0162f62e4435
 ---> 265493a76158
Step 10/10 : CMD ["./strapi.sh"]
 ---> Running in 51fafe469c68
Removing intermediate container 51fafe469c68
 ---> 09be8dd339ff
Successfully built 09be8dd339ff
Successfully tagged strapidocker_api:latest
```

**Comment by lucaperret** [comment]
Hi @ouchiko, could you try with the last image (3.0.0-alpha.14) and if it don't work, report this issue in the core Strapi's repository ?
