### ISSUE TITLE
Prod deploy into a separated container from the API module

### ISSUE THREAD

**Issue by jmchza** [strapi/strapi-docker#66]
**Informations**
- **Node.js version**:10.10.0
- **npm version**:6.4.1
- **Strapi version**:3.0.0-alpha.14.1.1
- **Database**:Postgres
- **Operating system**:Mac high Sierra

**What is the current behavior?**
What about running the admin console pointing to a separate api on another server ? 
that would be running the admin console with the addition of this, but not DB associated locally:

I would really appreciate your clarification on this one. thank you heaps in advance.

```
"admin": {
    "build": {
      "host": "http://localhost:4000/admin",
      "backend": "https://mydomain.com",
      "plugins": {
        "source":  "host",
        "folder": "/plugins"
      }
    }
```

would this work or the admin console would still to need to have access to the DB in order to start properly?
I just tried it and I get this errors:
```
[2018-09-21T12:49:10.128Z] info strapi-local-auth initialized
(node:2245) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
From previous event:
    at Client_PG.acquireRawConnection (/Workspaces/Storyx-WKS/admin-new/node_modules/knex/lib/dialects/postgres/index.js:147:12)
    at create (/Workspaces/Storyx-WKS/admin-new/node_modules/knex/lib/client.js:280:23)
    at tryPromise (/Workspaces/Storyx-WKS/admin-new/node_modules/tarn/lib/Pool.js:366:22)
    at tryPromise (/Workspaces/Storyx-WKS/admin-new/node_modules/tarn/lib/utils.js:57:20)
    at Promise (/Workspaces/Storyx-WKS/admin-new/node_modules/tarn/lib/Pool.js:366:5)
    at new Promise (<anonymous>)
    at callbackOrPromise (/Workspaces/Storyx-WKS/admin-new/node_modules/tarn/lib/Pool.js:357:10)
    at Pool._create (/Workspaces/Storyx-WKS/admin-new/node_modules/tarn/lib/Pool.js:307:5)
    at Pool._doCreate (/Workspaces/Storyx-WKS/admin-new/node_modules/tarn/lib/Pool.js:275:32)
    at Pool._tryAcquireOrCreate (/Workspaces/Storyx-WKS/admin-new/node_modules/tarn/lib/Pool.js:212:12)
    at Pool.acquire (/Workspaces/Storyx-WKS/admin-new/node_modules/tarn/lib/Pool.js:119:10)
    at /Workspaces/Storyx-WKS/admin-new/node_modules/knex/lib/client.js:335:26
From previous event:
    at Client_PG.acquireConnection (/Workspaces/Storyx-WKS/admin-new/node_modules/knex/lib/client.js:334:34)
    at Runner.ensureConnection (/Workspaces/Storyx-WKS/admin-new/node_modules/knex/lib/runner.js:228:24)
    at Runner.run (/Workspaces/Storyx-WKS/admin-new/node_modules/knex/lib/runner.js:34:42)
    at SchemaBuilder.Target.then (/Workspaces/Storyx-WKS/admin-new/node_modules/knex/lib/interface.js:20:43)
(node:2245) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:2245) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2245) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
```

**Steps to reproduce the problem**
Bring DB down and run npm start with a api component running on another server.

**What is the expected behavior?**
Run an admin console with not DB connection other than doing it thorough the API module 

**Suggested solutions**

**Comment by groteck** [comment]
This is related to the Postgress template needs to be a bool and on the strapi generated template it is loaded as strings change your `project_name/config/environments/production/database.json`

```
cat strapi/config/environments/production/database.json 
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "postgres",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "srv": false,
        "port": "${process.env.DATABASE_PORT || 27017}",
        "database": "${process.env.DATABASE_NAME || 'strapi'}",
        "username": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}",
        "ssl": false
      },
      "options": {
        "authenticationDatabase": "${process.env.DATABASE_AUTHENTICATION_DATABASE || ''}",
        "ssl": false
      }
    }
  }
}
