### ISSUE TITLE
Error installing with quickstart on Mac OSX

### ISSUE THREAD

**Issue by hesselbom** [strapi/strapi-docker#84]
Following this tutorial (https://medium.com/strapi/strapi-quickstart-with-docker-d77ca7c86c1f) and running `git clone https://github.com/strapi/strapi-docker && cd strapi-docker` followed by `docker-compose up` on Mac OSX I get the following error (instead of running at http://localhost:1337):

```
Starting strapi-docker_db_1 ... done
strapi-docker_api_1 is up-to-date
Attaching to strapi-docker_db_1, strapi-docker_api_1
db_1   | 2019-01-15T16:18:18.269+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
api_1  | error TypeError: strapi.models.core_store.forge is not a function
api_1  |     at Object.get (/usr/local/lib/node_modules/strapi/lib/core/store.js:55:47)
api_1  |     at module.exports (/usr/src/api/strapi-app/plugins/content-manager/config/functions/bootstrap.js:235:42)
api_1  |     at Promise (/usr/local/lib/node_modules/strapi/lib/Strapi.js:296:13)
api_1  |     at new Promise (<anonymous>)
api_1  |     at execBootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:284:11)
api_1  |     at Promise.all.Object.values.map.x (/usr/local/lib/node_modules/strapi/lib/Strapi.js:323:44)
api_1  |     at Array.map (<anonymous>)
api_1  |     at Strapi.bootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:323:35)
api_1  |     at Strapi.start (/usr/local/lib/node_modules/strapi/lib/Strapi.js:108:18)
api_1  | (node:17) UnhandledPromiseRejectionWarning: TypeError: strapi.models.core_store.forge is not a function
api_1  |     at Object.get (/usr/local/lib/node_modules/strapi/lib/core/store.js:55:47)
api_1  |     at module.exports (/usr/src/api/strapi-app/plugins/settings-manager/config/functions/bootstrap.js:17:26)
api_1  |     at Promise (/usr/local/lib/node_modules/strapi/lib/Strapi.js:296:13)
api_1  |     at new Promise (<anonymous>)
api_1  |     at execBootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:284:11)
api_1  |     at Promise.all.Object.values.map.x (/usr/local/lib/node_modules/strapi/lib/Strapi.js:323:44)
api_1  |     at Array.map (<anonymous>)
api_1  |     at Strapi.bootstrap (/usr/local/lib/node_modules/strapi/lib/Strapi.js:323:35)
api_1  |     at Strapi.start (/usr/local/lib/node_modules/strapi/lib/Strapi.js:108:18)
api_1  | (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
api_1  | (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm running Mac OSX 10.14.1 and Docker Desktop Community 2.0.0.2 (engine 18.09.1).

**Comment by Klian** [comment]
Same error here.

**Comment by hesselbom** [comment]
Looks like I found a workaround. In `docker-compose.yml` it looks to mount to the folder `./strapi-app` but that folder doesn't exist. So by creating an empty folder with that name it works. So the steps to init a new project would be:

```shell
git clone https://github.com/strapi/strapi-docker
cd strapi-docker
mkdir strapi-app
docker-compose up
```

**Comment by lauriejim** [comment]
Can you give us an update please.
Based on last version of files.

**Comment by alexandrebodin** [comment]
HI, 

We just released a full rebuild of our docker image 🎉 
We are closing the issues and open PRs to start fresh.

If you feel like something is missing or want to add things feel free to open new PRs ! 💯
